### ISSUE TITLE
cmake biogears error

### ISSUE THREAD

**Issue by ahamdy47** [AdvancedModularManikin/DDS#4]
Hi Keepers of AMM repo, I am trying to install AMM on an Ubuntu 18.04 with an x86_64. I have followed your guideline to the tooth yet I am getting an error when building AMM using CMake. besides installing few more dependencies then what was listed (on Biogears git) I cloned your forked version of Biogears/core and ran "cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release .." in dir AMM_Modules/build yet I am getting this error message "CMake Error at support/CMakeLists.txt:9 Unknown CMake command 'stage_biogears_schema'" . Biogears_FOUND is set to 1 so I know I have a little progress but I do not know if this is a CMakeLists.txt file issue you need to update or I am doing something wrong?
Thanks in Advance!

**Comment by riggs** [comment]
I apologize for the confusion, but the forks of biogears in this org are outdated and not what we actually use. Additionally, as stated in the readme, this whole repo is basically deprecated and is being kept here for support of legacy hardware.

There will be a new repo on the AMM org created within the next week or so that will be the actual library you want to use for any future development with AMM. As soon as it's up, we'll be sure to update links on the main website, as well as here.
